### PR TITLE
basic dockerfile

### PR DESCRIPTION
**Pull request by g00gol**

### CODE REVIEW

**Comment by g00gol** [comment]
@bigguyhere @iscii @moyales i cannot proceed with this issue until we fix several typescript errors listed below:

```
> client@0.0.0 build
> tsc && vite build

src/components/PlaceCard.tsx(9,1): error TS6192: All imports in import declaration are unused.
src/components/PlaceCard.tsx(11,1): error TS6133: 'TripData' is declared but its value is never read.
src/components/PlanLine.tsx(23,26): error TS2345: Argument of type 'PlanMarkerProps | undefined' is not assignable to parameter of type 'PlanMarkerData | undefined'.
  Property 'location' is missing in type 'PlanMarkerProps' but required in type 'PlanMarkerData'.
src/components/PlanLine.tsx(34,9): error TS2322: Type 'undefined' is not assignable to type 'PlanMarkerProps'.
src/components/PlanLine.tsx(35,9): error TS2322: Type 'undefined' is not assignable to type 'PlanMarkerProps'.
src/components/PlanLine.tsx(61,50): error TS2339: Property 'location' does not exist on type 'PlanMarkerProps'.
src/components/PlanLine.tsx(62,51): error TS2339: Property 'location' does not exist on type 'PlanMarkerProps'.
src/components/PlanLine.tsx(68,49): error TS2339: Property 'location' does not exist on type 'PlanMarkerProps'.
src/components/PlanLine.tsx(69,50): error TS2339: Property 'location' does not exist on type 'PlanMarkerProps'.
src/components/auth/ForgotPassword.tsx(1,17): error TS6133: 'useEffect' is declared but its value is never read.
src/components/auth/ResetPassword.tsx(1,17): error TS6133: 'useEffect' is declared but its value is never read.
src/components/auth/ResetPassword.tsx(1,28): error TS6133: 'useState' is declared but its value is never read.
src/components/auth/ResetPassword.tsx(6,23): error TS6133: 'setSearchParams' is declared but its value is never read.
src/components/auth/Signin.tsx(11,9): error TS6133: 'forgot' is declared but its value is never read.
src/components/auth/Signin.tsx(11,17): error TS6133: 'setForgot' is declared but its value is never read.
src/contexts/TripContext.tsx(20,10): error TS6133: 'loadingTrip' is declared but its value is never read.
src/contexts/TripContext.tsx(20,23): error TS6133: 'setLoadingTrip' is declared but its value is never read.
src/contexts/TripContext.tsx(21,9): error TS6133: 'currentUser' is declared but its value is never read.
src/dataObjects/TripData.tsx(1,1): error TS6133: 'PlaceData' is declared but its value is never read.
src/main.tsx(12,7): error TS6133: 'app' is declared but its value is never read.
```

**Comment by g00gol** [comment]
will be addressing the ts lint issues in #14

**Comment by g00gol** [comment]
requesting review. please run `docker-compose up` in root directory. you should then be able to access the client on localhost:3000 and api docs at localhost:8000/docs

**Comment by iscii** [comment]
unable to access ports (on wsl) -- need another reviewer to test

**Pull request merged**
