### PR TITLE
authentication and stuff

### PR DESCRIPTION
**Pull request by g00gol**
setting up firebase authentication

### CODE REVIEW

**Comment by g00gol** [comment]
@iscii i need you to provide me with a working auth token to test the backend route. i tested with an old one and it says expired (expected)

**Comment by g00gol** [comment]
token auth is done and tested

**Comment by g00gol** [comment]
@iscii finish the frontend changes u wanted on this branch and we can merge

**Comment by iscii** [comment]
gud

**Review by iscii — APPROVED** [review]

**Pull request merged**
